### ISSUE TITLE
Clarify Governor & Lt. Governor Wages

### ISSUE THREAD

**Issue by straw-mann** [D3nnis3n/White-Tiger-Feedback#1]
The constitution states that governors are paid a wage from the state treasury, AND a federal wage as members of the Senate. Is the intended situation one or the other, or both? If the intent is both, so that governors receive two paychecks, this should be stated.
![wages](https://user-images.githubusercontent.com/88129104/127437810-e7d2ae2a-7704-488e-a860-10b98a0d53d4.png)

**Comment by D3nnis3n** [comment]
The difference is the "shall". The payment from federal task is mandatory, the one from the state treasury optional - at least for now. What would you change to make this more clear?

**Comment by straw-mann** [comment]
I would add a clause to the beginning of sentence 4.1.3: "In addition to any compensation that may be paid by their respective States, each Member of the Senate shall be paid a wage according to the wage index out of the funds of the Federal Government."

**Comment by D3nnis3n** [comment]
Fixed.
