### ISSUE TITLE
Food Balance Suggestion: Crafting Resource Discount granted by Skill Gain from Food

### ISSUE THREAD

**Issue by straw-mann** [D3nnis3n/White-Tiger-Feedback#10]
I believe the chart explains the whole idea -
![food](https://user-images.githubusercontent.com/88129104/128273753-3e4994e3-7822-48f9-9a77-9edbfcd9d1a6.png)

**Comment by D3nnis3n** [comment]
Hey,
that is something that would only be possible with a mod or a main game change.

I'd recommend you to post that suggestion over on https://github.com/StrangeLoopGames/EcoSuggestions/issues, where it will have more effect than it could here, as we neither have modders actively working for WT nor does SLG create game features specifically for WT.
