### ISSUE TITLE
Add Nutrient Paste as required bunker food

### ISSUE THREAD

**Issue by DanielKispert** [D3nnis3n/White-Tiger-Feedback#11]
right now the meteor lab needs only some advanced cooking + advanced baking meals.
With the food rebalancing, and the goal-based endgame thingy, it would be cool to not have to store thousands of food inside the bunker and count them for "did they really do this goal".
Can we add an item "Nutrient Paste" (maybe hydrocolloids or whatever as picture) that has the calorie total of the meals required right now, but it's made from all the possible meals at adv baking and adv cooking together (weighted by calories of those meals). So e.g. you'd need twice as many of a 700 calorie food as of an 1400 calorie food so their amounts average out. This would be not eatable (cause it's for endgame and a goal) and you'd need to have 100 of them in the food bunker, so the GMs can easily count and verify. It could be made at the laboratory, like the modern skill scrolls, but with no skill and default labor.

**Comment by DanielKispert** [comment]
Suggested name: "Concentrated Calorie Manifold"
Recipe:
![grafik](https://user-images.githubusercontent.com/34270661/128606232-96703cde-4f95-4f0e-ba7f-ca2c4ce0e48c.png)
Contained calories: 1,48 million (compared to the ~3.2 million calories of the current meteor lab, but weighted since farming calories got 10-30 times harder to acquire)

**Comment by D3nnis3n** [comment]
Already implemented.
