### ISSUE TITLE
Bundle 5 Fertilizers into one

### ISSUE THREAD

**Issue by DanielKispert** [D3nnis3n/White-Tiger-Feedback#12]
makes the bigger requirement for fertilizing actually doable (suggestion from leuchtturm that actually had a huge farm once)

-> increase fertilizer power and needed ingredients for fertilizers by x5 and lower weight by half

**Comment by DanielKispert** [comment]
feedback from rev: all fertilizers but limestone and compost are useless. Proposal: Compost fertilizer compost needs x10

**Comment by D3nnis3n** [comment]
Merged with #18
