### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by DanielKispert** [D3nnis3n/White-Tiger-Feedback#16]
- switch minting item from LCP to copper bars, 1 copper ore for 1000€ equivalent
- uni buys unlimited amounts of research papers that get smite when inventories are full
- fed bank buys and sells LCP for 100€ each

**Comment by D3nnis3n** [comment]
Why Gold how much gold

Daniel ***@***.***> schrieb am Mi., 18. Aug. 2021, 06:04:

**Comment by D3nnis3n** [comment]
fuck this

**Comment by D3nnis3n** [comment]
Better solution found with UBI. Thanks for your suggestion.
