### ISSUE TITLE
States Unable to Spend Donation Receipts

### ISSUE THREAD

**Issue by straw-mann** [D3nnis3n/White-Tiger-Feedback#2]
It appears that, due to this section of the Currency and Trade Regulations law, there is no way for state governors to pay for goods using Donation Receipts.

![dr1](https://user-images.githubusercontent.com/88129104/127448518-44f13344-0fd5-405c-a7f3-a9d0b11b405c.png)

I may be misinterpreting due to a display bug - this has happened to me before, and since Currency and Trade Regulations is constitutional, I can't look at the editable version of the law to confirm. However, this error message posted by Xozdragon appears to confirm my theory -

![dr2](https://user-images.githubusercontent.com/88129104/127448632-710a82c3-e845-4d89-bb4b-5bcada8c9619.jpg)

that it's only possible to trade in Donation Receipts on the listed properties, none of which are accessible to state officials. Furthermore, the four states with no access to listed properties spent no DRs this cycle:

![dr3](https://user-images.githubusercontent.com/88129104/127448653-779b9c1c-0bf5-490c-a1e3-dfc3d25a4c8d.png)

Modifying "Currency and Trade Regulations" subsection "Personal Credit Restrictions" as follows should resolve the issue. Donation Receipt transactions should be allowed on the listed properties, OR if (1. buyer has one of the ten titles "Governor/Lieutenant Governor/Mayor/Deputy Mayor of [State]" AND 2. buyer is owner of property). Part 1 allows state officials to transact in DRs, but only on the buy side; Part 2 guarantees that DR transactions will happen at a shop owned by the state official, preventing DR purchases from other players' shops.

**Comment by DanielKispert** [comment]
![grafik](https://user-images.githubusercontent.com/34270661/127529284-5595d517-295e-4a0f-93a7-e44cefc2387f.png)

**Comment by straw-mann** [comment]
This resolves the issue. Would it be administratively simpler to add an empty "States DR Trade Zone" district to the constitutional law, then simply fastpass modifications to that district to add or remove DR shops? This would prevent GMs having to additionally edit the constitutional law each time a shop is added or removed.

**Comment by DanielKispert** [comment]
there is no district table above ground that a citizen could edit to modify the district so we'd need to edit it ourselves. Will think about it.
