### ISSUE TITLE
Research still too slow

### ISSUE THREAD

**Issue by DanielKispert** [D3nnis3n/White-Tiger-Feedback#21]
this run, we tried out 30/20/10 as book costs (meaning a book takes 30 times the basic papers of a single scroll, 20 times the advanced and 10 times the modern ones). The runs before, it was 20/20/20. Since we have day 14 and research is not done (we are missing electronics, composites, oil drilling, advanced masonry, advanced cooking and advanced baking), let's try 20/15/10 next run

**Comment by D3nnis3n** [comment]
Done
