### ISSUE TITLE
Index linked pensions 

### ISSUE THREAD

**Issue by Dementor93** [D3nnis3n/White-Tiger-Feedback#23]
It could make sense to give the government officials an index linked pension. That is, linked to the wage index. That way the amount being paid out is befitting the current economic situation, not the one during their time in office. 

By adding the % from the wage index (Constitution attatchment 1) cumulatively to the custom stat for pensions. Pension pay can thus be (custom pension stat * index).

**Comment by D3nnis3n** [comment]
Hello Dementor,
thanks for your feedback.

I'm not sure I understood you right, but are you aware that the pension paid out is _always_ based on the _current_ wage index?
If i understood you correctly, that would already be the behaviour you requested?

**Comment by D3nnis3n** [comment]
So, if a Senator has worked for 7 days he has accumulated 7 x 2,25% = 15,75 % of his 42,5% of the salary pay scale as a pension.
My maths was bad, but that should be 6,7 % of the reference salary at any given time being paid out as pension.

**Comment by D3nnis3n** [comment]
I was just told by Daniel that exactly this is not the case, sorry, lol. We're considering it.

**Comment by D3nnis3n** [comment]
Approved.

**Comment by DanielKispert** [comment]
vote4close, done

**Comment by D3nnis3n** [comment]
Done.
