### ISSUE TITLE
Election

### ISSUE THREAD

**Issue by Dementor93** [D3nnis3n/White-Tiger-Feedback#24]
There seems to be a slight miss match between the way elections are held and the letter of the law. Constitution §3.3 and §6.2 both state that elections are to be done trough relative majority (first past the post systems), but they are in fact done trough instant runoff voting.

Now, I would argue that instant runoff voting is in fact better, but maybe change the constitution to reflect that? 

I might be wrong, since I haven't actually seen an election with more than two people yet. But the voting page claims its an instant runoff election.

Suggestion: 
- Change all instances of "relative majority", to "Instant runoff voting"

Sources (Wikipedia as a source.... XD): 
https://en.wikipedia.org/wiki/Plurality_(voting)#:~:text=A%20plurality%20vote%20(in%20the,half%20of%20all%20votes%20cast.
https://en.wikipedia.org/wiki/Instant-runoff_voting

**Comment by D3nnis3n** [comment]
"relative majority" is a legal term for a majority that is highest value of votes in a election winning, Instant-Runoff voting is a type of voting, but doesn't specify a majority. Instant-runoff voting can also be done with a absolute majority (50% needed or no winner), or with other majorities, so the constiution is correct in regards to this.

**Comment by D3nnis3n** [comment]
![image](https://user-images.githubusercontent.com/25908592/131417221-2ca28a59-a86b-47ca-b002-2c358a804a16.png)
