### ISSUE TITLE
Land Claim Paper Rework

### ISSUE THREAD

**Issue by DanielKispert** [D3nnis3n/White-Tiger-Feedback#25]
The following suggestion assumes that the changes detailed in https://github.com/D3nnis3n/White-Tiger-Feedback/issues/17 have been applied.

Since LCPs will be craftable in the future, we could try to replicate this already like we've done with the University.
The main changes would be:
1. you no longer get 5 LCPs by reading a Skill Scroll - this could be achieved by using Monzun's mod
2. LCPs are craftable and traded by a central authority

Things that are still open and would need to be discussed:
1. the exact recipe of LCPs, probably like Paper + Coal (or something else to write with)
2. who is the central authority to craft and trade LCPs. Options: Federal Bank or Federal Government
Federal Bank: lowers impact of UBI-caused inflation (needs to print less money because it flows back through LCP purchases). Federal Government: additional income source next to taxes
3. will citizens still spawn with 10 LCP or more (e.g. 20) to offset the central authority not being filled in the first 24h

**Comment by DanielKispert** [comment]
answers for open points 1-3:

1. Recipe: 1 Paper, 1 Huckleberry + 1 Crushed Coal (for the ink), 1 Cloth (ribbon) and 1 Copper Bar (Stamp). Needs skills Tailoring and Smelting => takes probably 24h before they can be crafted by gov
2. Federal Government, only PM can craft them
3. they should spawn with 20 LCP because tailoring and smelting is needed to craft LCP + the PM needs to set it up

=> which table will they be crafted at? probably carpentry table or tailoring table?

**Comment by D3nnis3n** [comment]
1. Paper, Charcoal (Ink), Cloth + Huckleberry (ribbon), Tallow (Wax for stamping) 
2. Yes, Federal Government grounds (the plot shouldnt be named PM Office, but Federal Government, actually), but PM only for now.
3. Should be a government object, not a user object. Mint possible?

**Comment by DanielKispert** [comment]
vote4close, done

**Comment by D3nnis3n** [comment]
Done.
