### ISSUE TITLE
Stock Market Proposal

### ISSUE THREAD

**Issue by straw-mann** [D3nnis3n/White-Tiger-Feedback#3]
**Preface: This is, I believe, a complete plan for running a stock market on White Tiger using only vanilla game features. After writing it down and considering its complexity and risks - particularly the necessity of an incorruptible Fed Bank director who plays full-time for the entire cycle - I think it will be wiser for me to develop the mod described below before advancing this proposal any further. Nevertheless, the plan is presented here for interest and discussion.**

---

Running an in-game stock market by hand will be a lot of work, requiring an active Federal Bank director focusing on the task all cycle. The good news is that, if a trial run of the stock market is successful and its effects are desirable for the server, most of the work can be automated in a mod, making future cycles' stock markets much easier to operate.

Many of the details in this document use round numbers and inflexible rules to make manual operation of the market feasible using existing in-game mechanics, and can be made more flexible if the trial is successful and a stock market mod is created.

First, a few rules for the shares.

- When a company is formed, it is issued a fixed number of shares (1000) divided equally among its members.

- Shares are for investment purposes only, and confer no management, ownership or voting rights - similar to real-life [preferred shares](https://en.wikipedia.org/wiki/Preferred_stock). It's unlikely anyone wants to be told how to play the game by their virtual investors.

- Companies may issue dividends at their discretion, subject only to the requirement that each share receive an equal dividend.

How does a company become publicly listed?

- Upon formation, a company may choose to become public.

- If it makes this choice, the Federal Bank retains 20% of the company's shares (200 shares).

- Since the wealth and assets of a company upon formation should in most cases be 0, the whole value of its stock is its projected future earnings. The Federal Bank director could analyze the company's skills and business plan, then value the stock based on a discretionary estimate of the company's prospects - or, for smooth operation of the trial, this value could be fixed at €10.000, giving every company's shares an initial price of €10.

- The Federal Bank compensates the company for the retained shares at the initial price (200 shares x €10 = €2000).

So how do I "ape in" to "hodl stonks" "to the moon"?

- The Federal Bank acts as [market-maker](https://en.wikipedia.org/wiki/Market_maker) - the institution which both buys and sells shares at all times, profiting on the spread between the buy and sell prices.

- It does this by configuring a currency exchange to sell 10 [Company] Shares for €11, and to buy 10 [Company Shares] for €9. This currency exchange is accessible to all players; it serves as the "stock exchange".

- If all 10 of the offered shares are bought, the bank offers 10 more shares at €12, and adjusts its buy price to €10.

- If 10 shares are sold to the currency exchange, the bank offers to buy 10 more at €8, and adjusts its sell price to €10.

- This process continues throughout the cycle, with adjustments to both price and quantity occurring at the director's discretion.

- Obviously, there is tremendous potential for corruption, collusion and self-dealing on the part of the market-maker, which is why real-life market-makers are heavily regulated. For the purposes of this trial, the director should, at the very least, be prohibited from personally holding any shares, and should occasionally be audited by an admin to the extent the transaction log allows.

- During the trial, stock trading should only be allowed at the Federal Bank's currency exchanges - not directly between players.

What happens if everyone in the company quits?

- Once the last member enters the "Abandoned" demographic, the Federal Bank can begin "bankruptcy proceedings".

- Trading in the company's shares is halted.

- The company's assets are seized and liquidated.

- The proceeds are distributed proportionally among the surviving shareholders.

Without the equity ownership and voting rights afforded by real-life [common stock](https://en.wikipedia.org/wiki/Common_stock), these shares should derive most of their investment value as follows:
1. For shares of active, profitable companies - dividends and the prospect of higher future dividends.
2. For inactive companies - speculation on the value of soon-to-be-seized assets.
3. For the investor - as a shelter from the income tax.

To encourage general participation in this somewhat complicated and risky trial, the purchase of shares as an income tax shelter should be preserved and encouraged, and dividends should be tax-free. The only source of government revenue from stocks should, at first, be the Federal Bank's market-making profits; a capital gains tax should only be implemented after the stock market has been proven to work, any flaws in the system have been resolved, and broad participation has been established.

**Comment by straw-mann** [comment]
Disappointingly, Eco does not support custom interface panels in mods. Until it does, a stock market mod is not realistic.

**Comment by D3nnis3n** [comment]
I'd suggest you to rewrite the suggestion a bit and put it over on https://github.com/StrangeLoopGames/EcoSuggestions/issues
It's well written and should not get lost.
