### ISSUE TITLE
Replace Skill rule with constitutional tax

### ISSUE THREAD

**Issue by DanielKispert** [D3nnis3n/White-Tiger-Feedback#33]
not finished yet, collecting things to do:

1. remove the skill rule from the constitution
2. create titles like "Company - 2 Members", "Company - 3 Members" and so on
3. the "registered company" title will contain all of these titles and nothing else
4. registering a company will be required to collaborate with friends (TBD: will inventory access be blocked otherwise?)
5. a company can be registered by making a title, naming it like the company, adding all friends as holders and then setting **only** Game Masters as managers so the amount of people can not be changed afterwards
6. either all company members need to be managers of the company account(s) or the company leader ensures all taxes of employees are paid
6. if a citizen sells something, a tax is added to them personally. The tax is 10% of sale amount for a 2 person company, 20% for a 3 person company, 30% for a 4 person company, capped at 75% at 9 members. This tax is put into the Federal Bank account. (TBD: edge cases, abusable by lowering prices? abusable by using contracts etc?)
7. if a citizen buys something at a store and is in a company, they receive a tax rebate of 10% of the buy amount against this tax (TBD: how to be not abusable by trading with friends, fair for solos?)

**Comment by DanielKispert** [comment]
vote4close, done

**Comment by Tralolol** [comment]
Is this just a VAT tax for companies only? Am I understanding correctly that the limitations will be replaced with this, with the goal in mind to balance non skill capped companies?

I think its a great idea if so, however , the tax rates seem kind of low vs the benefit of , say, a group of 3 having 6 stars on day 2 vs 2 stars. I would gladly pay a tax of 30% as a solo to have 4 extra stars, not to mention man power, and I definitely could put a group of 3 solid players together and dominate all solo players out of the market if that was my goal.

**Comment by DanielKispert** [comment]
closing because done, I think @Tralolol 's question was answered in discord already?
