### ISSUE TITLE
Steel costs too much coal

### ISSUE THREAD

**Issue by thomasfn** [D3nnis3n/White-Tiger-Feedback#34]
At maximum efficiency using T2 equipment (Mechanics level), Steel Bars require a disproportionate amount of coal. The ratio doesn't change much with T3 equipment.

Currently it costs ~1.7 pieces of iron ore, 1.9 pieces of limestone and 5 pieces of coal per steel bar. That's roughly 58% of the cost of steel coming _just_ from coal. Aside from making steel (and coal due to incredibly high demand) really expensive for no good reason, it's also really boring just constantly needing coal and barely anything else. A little bit of cursory googling reveals that, in the real world, steel actually has barely any carbon in it at all, a couple of percent at most, so there's some big questions about the physical accuracy here too.

Charcoal is not usually a viable alternative as it costs 3.5 logs per piece and logs are usually in very short supply and highly valued on WT due to high demand for research papers.

A quick way to level out the recipe a bit would be to make the coal requirement a dynamic component meaning that the upgrades work on it. Then the recipe would only need ~2.4 pieces of coal, which is still higher than the other components but is a bit more balanced.

Here are my calculations:
```
== TIER 2 (Mechanics) ==

Coal: ~58%
Limestone: ~22%
Iron: ~20%

1x Steel Bar = 0.95 Iron Bar + 1 Quicklime + 1 Crushed Coal
             = 1.6921875 Iron Ore + 1.9 Limestone + 5 Coal (8.5921875)
1x Quicklime = 0.475 Crushed Limestone
             = 1.9 Limestone
1x Iron Bar = 0.2375 Iron Conc = 1.78125 Iron Ore

1x Iron Conc = 1.5 Crushed Iron = 7.5 Iron Ore

1x Crushed Iron = 5 Iron Ore
1x Crushed Limestone = 4 Limestone
1x Crushed Coal = 5 Coal

== TIER 3 (Industry) ==

Coal: ~57%
Limestone: ~27%
Iron: ~16%

1x Steel Bar = 0.95 Iron Bar + 1 Quicklime + 1 Crushed Coal
             = 1.128125 Iron Ore + 1.9 Limestone + 4 Coal (7.028125)
1x Quicklime = 0.475 Crushed Limestone
             = 1.9 Limestone

1x Iron Bar = 0.2375 Iron Conc = 1.1875 Iron Ore

1x Iron Conc = 1.25 Crushed Iron = 5 Iron Ore

1x Crushed Iron = 4 Iron Ore
1x Crushed Limestone = 4 Limestone
1x Crushed Coal = 4 Coal
```

**Comment by revtje** [comment]
I second this. With all the steel required for research, ashlar, tools, machinery it feels like you do nothing but mine coal. It gets to a point where mining iron feels like a refreshing and almost weird thing to do.

At first I liked the change because it opened up a business opportunity to become a coal miner but unfortunately its very rare to see a lot of coal miners

**Comment by Elmeye** [comment]
I will third this, having mined an upsetting amount of coal I feel that coal cost could do with being more in line with the limestone cost.

**Comment by DanielKispert** [comment]
coal will be dynamic for WT27 -> vote4close

**Comment by D3nnis3n** [comment]
Done.
