### ISSUE TITLE
Enforcing server rules (general WT Feedback)

### ISSUE THREAD

**Issue by lucasagostini** [D3nnis3n/White-Tiger-Feedback#38]
Me and my group felt very annoyed by some things that happened during this WT cycle, and since was our first I would like to point them so we could improve them to the next cycles.

We have strong feelings about rules being enforced or removed. When we built our home in Unica, we followed all the rules: realistic building, no wood after day X, no visible stockpiles, etc. If this are not rules that are set in stone, why even mention them? In our opinion, they would make WT great, and we followed all of them. 

I just logged in after a few days where we had close to nothing to do, and saw Syd petrol farm over the water. "oh, but the rule says that this is only allowed if government allows it", well, he is the government so he should not be able to allow himself to do something like that. (Image shows his petrol farm floating on water....)

What made us LOVE WT, and even find the game boring in other servers, were the rules and the ability to produce a nice world and buildings with a lot of coop. What we saw on real life was not exactly that, lots of unfinished buildings that can't be destroyed or unclaimed (even if someone abandoned them) because constitution states that they can only be removes if the land will be used. Lots of people trying to break the rules or circumvent them, TONS of people that complain and are worried about the "smallest" things and are not about stuff that really matter. 

I am sorry about the long rant.
![image](https://user-images.githubusercontent.com/11837075/138185991-35d984f5-bcb1-43ff-b122-4d67272ac347.png)

As a suggestion, I would make those server rules and the GM able to enforce them without needing the government for it.

**Comment by D3nnis3n** [comment]
As a general concept change we have decided on purpose to keep rules to basic setup stuff of WT in the future and have the rest be dealt with by player justice itself. This does save GMs a lot of work that simply isn't available and ensures the spirit of WT as a player managed server.

The enforcement of law is up to the executive and the judiciary, typically with a bit of political leeway. If you feel that law is not executed correctly by the executive, the correct way is to compel them to by opening a law case with the judiciary.

We do not plan to change this back to server rules in any case.
