### ISSUE TITLE
Contract Boards being Spamed, reputation system being used poorly and GM approving it.

### ISSUE THREAD

**Issue by lucasagostini** [D3nnis3n/White-Tiger-Feedback#39]
![image](https://user-images.githubusercontent.com/11837075/138209344-df2efc9e-344c-40c0-9aab-a8d8aeed4eaf.png)

One player, name SNK, tried to complain about two actions that he thought were abusing game mechanics, as stated in 2.4 in the following message: 

https://discord.com/channels/254025510651297802/606205030344687616/900586381691207751

According to the GM that replied it (in the image attached), this is the intended way to use contract boards and using the reputation system.

So I would like to suggest that both of these are reviewed. If contract boards are intended to be used to spam your business (instead of making contracts), I would like it to be changed since I don't think this is fair.

If the reputation system is intended to give bad reputation without a reason, or "just because I like to see names go red" as the message below:
https://discord.com/channels/254025510651297802/606205030344687616/900594554087030824
I would like it to be changed as well. I trusted the reputation system inside the game and used it accordingly, but if a GM, who knows more about the game than I do, says this is the intended way, please could you change it?

I also would like to ask for more clarifications from GMs, some of them are really nice and explain everything very thorughly, while others (like the one from this specific case) seem to take split second decisions and then don't accept when they are questioned about it. The proper answer (in this case) would be something along the lines of "we will look into it, and if he is abusing game mechanics we will take the measures that are necessary". 

It is not the first time this person acts like this, and in my honest opinion this is not the way a GM should act or proceed when being questioned, because I (as a player) just wanted clarification on HOW this is the way both of those systems are intended to be used.

**Comment by D3nnis3n** [comment]
Reputations can contain no message, but if they do, they need to be:
- Non insulting
- Defined, so the reader knows what it is about
- A legit opinion or a matter of fact, but not a wrong 'fact'

The GM is on her fourth day, give her some leeway to learn stuff, no need to complain like this publically, a simple DM would have been sufficient.
