### ISSUE TITLE
Great Monument

### ISSUE THREAD

**Issue by PhillyJay** [D3nnis3n/White-Tiger-Feedback#44]
In remembrance of our greatest citizen president, I would like every White Tiger cycle to have a pre-built 10 by 10 by 20 statue of my characters model from the cycle of which I served as a citizen president. I would like the statue to be built out of gold concentrate. I would also like access to this plot as my own personal property.
Dennis can have a statue too, but not as big, and his shall be made out of iron concentrate.

The citizens shall need not ever forget, the good things I did for them, the risks I took.

**Comment by D3nnis3n** [comment]
Rejected without comment, lol.

**Comment by DanielKispert** [comment]
Approve this or we riot.

EDIT: Riot on the 1st sunday of new WT at 20:00 in front of the spawn. Bring torches and pitchforks and signs saying "PJ for prez" :^)
