### ISSUE TITLE
Written (F1) Senate Laws stay through iterations but code laws are removed

### ISSUE THREAD

**Issue by DanielKispert** [D3nnis3n/White-Tiger-Feedback#49]
=> it's kind of backward, the code has no "meaning" as the written laws are the valid ones, but writing working code takes a lot more time. We should think about also persisting code laws somehow.

**Comment by D3nnis3n** [comment]
Bit boring if a full legislation is around, what do we need the Senate for?
Sure, can try around a lot, but for pretty much everything there is a BiS meta solution.

**Comment by DanielKispert** [comment]
true, also kind of dumb to have to build a senate full of courts and stuff every run.
