### ISSUE TITLE
change activity requirement of government officials

### ISSUE THREAD

**Issue by DanielKispert** [D3nnis3n/White-Tiger-Feedback#53]
Right now, government officials get automatically booted if they lose the "active" demographic.
This leads to two things:
1. people that lose active by accident have to get reelected
2. if the office should be replaced and it's not a friday, the GMs have to start the election because noone else is allowed to

we should check if it's possible to rephrase the offices like this:
- you do not get autokicked if you lose the "active" demographic
- but everyone can start an election for your office if you aren't
=> that way people can easily rejoin an office if they lose active by accident and if someone wants to replace them because the official is inactive, they do not have to wait for a GM to start the election

**Comment by D3nnis3n** [comment]
I'm not convinced that will really lead to people stepping up to start an election, given mostly everyone just complains, but is not wanting to run themselves. Also, it might be overseen there is an election when normal players start it and there is no GM announcement on it. How do you want to solve this?

**Comment by DanielKispert** [comment]
> I'm not convinced that will really lead to people stepping up to start an election, given mostly everyone just complains, but is not wanting to run themselves. Also, it might be overseen there is an election when normal players start it and there is no GM announcement on it. How do you want to solve this?

agreed that the extra election might be overseen then. I see this not as a perfect, or even good solution, but a solution that's better than what we have right now. We GMs could/should still look for this ourselves and trigger the replacement elections ourselves too, but it additionally solves two problems we're having, people having to wait for us in case they're motivated and people getting kicked by accident and then having to wait pro forma.

**Comment by DanielKispert** [comment]
big issue: people shouldn't get paid while not active so this makes this approach a lot more complicated so adios
