### ISSUE TITLE
[Feature Request] Shoveling %cal bonus 

### ISSUE THREAD

**Issue by DinosaurDundee** [D3nnis3n/White-Tiger-Feedback#66]
Would be very handy to have a job benefiting a Shoveling bonus.

Shoveling is heavily required during T1&T2, for landscaping, road laying, and clay/sand gathering.

Could make sense to apply the shoveling bonus to Farming job, in addition to the %cal bonus on Hoe or as a choice, Hoe or Shovel.

**Comment by D3nnis3n** [comment]
Moved to https://github.com/StrangeLoopGames/EcoSuggestions/issues/1598, as it is a general game suggestion.
