### ISSUE TITLE
[Feature Request] Add under water plants/animals farming 

### ISSUE THREAD

**Issue by DinosaurDundee** [D3nnis3n/White-Tiger-Feedback#67]
Unless I am mistaken, under water plants do not generate seeds and cannot be manually planted.

This would be a nice feature to farm Kelp (fiber + sushi), or just to design better looking under water environment / water tanks.

In addition, it would be nice to be able to craft oyster/mussel farming ports - in addition to fish traps, except these would go on seashore.

**Comment by D3nnis3n** [comment]
Moved to https://github.com/StrangeLoopGames/EcoSuggestions/issues/1597, as it is a general game suggestion.
