### ISSUE TITLE
Daily calorie limit for work parties

### ISSUE THREAD

**Issue by EddEco** [D3nnis3n/White-Tiger-Feedback#7]
This is a proposal to create a law that limits the amount of calories a single player can put into any work parties per day. The idea is to ensure that there is more competitive pricing around work parties by limiting supply of labour, and ensuring that work party revenue is more available to more players.

The limit could be created in law, by creating a stat that is tracked. A sensible limit might be somewhere between 20'000 and 100'000 labour per day, obvious with testing. Once all the daily work party labour is exhausted, it would be an opportunity for someone else to complete other work parties.

**Comment by DanielKispert** [comment]
the senate can vote on this, not really something we'd need to add ourselves (or anyone can ask for a referendum)

**Comment by D3nnis3n** [comment]
This indeed is a decision the Senate has to make, there is no visible reason why this is something that is necessary to enforce by constitutional or rule means.
