### ISSUE TITLE
[Feature Request] Cosmetic Add sprinklers option for pipes

### ISSUE THREAD

**Issue by DinosaurDundee** [D3nnis3n/White-Tiger-Feedback#75]
On WT crops have to be watered, which makes sense.

Currently people the drop an open ended pipe in their fields, would be nice to have a Sprinkler option when placing the pipe segment, so it would generate small particles on left and right sides. 

This would also allow the pipe to continue rather than being a dead end.

**Comment by D3nnis3n** [comment]
Moved to https://github.com/StrangeLoopGames/EcoSuggestions/issues/1595 due to being impossible to implement on WT without new game features, even when specifically intended for WT.
