### ISSUE TITLE
[Feature Request] Shop - Auto-repair

### ISSUE THREAD

**Issue by DinosaurDundee** [D3nnis3n/White-Tiger-Feedback#78]
Would be very nice to be able to configure a shop to automatically repair tools, or have a new dedicated shop station.

The player could for example set the repair price, and the repair would only be available if the shop has enough materials to repair the tool.

**Comment by D3nnis3n** [comment]
Moved over here, as it is a general game suggestion: https://github.com/StrangeLoopGames/EcoSuggestions/issues/1594
